choco install -y googlechrome
choco install -y firefox
choco install -y opera-gx
choco install -y 7zip.install
choco install -y notepadplusplus.install
choco install -y vlc
choco install -y sysinternals
choco install -y gimp
choco install -y git.install
choco install -y github-desktop
choco install -y gh
choco install -y nodejs.install
choco install -y python
choco install -y curl
choco install -y wget
choco install -y atom
choco install -y sumatrapdf.install
choco install -y chocolateygui
choco install -y windows-iso-downloader
choco install -y microsoft-windows-terminal
choco install -y youtube-dl
choco install -y croc
choco install -y choco-cleaner
choco install -y choco-upgrade-all-at-startup
choco install -y tor-browser
choco install -y powershell-core
choco install -y rufus
choco install -y aria2
choco install -y powertoys
choco install -y cmder
refreshenv
